import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar/Navbar";
import { Hero } from "./home/hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="overflow-y-hidden font-vt bg-[#1e66f5] text-text pb-8"> */}
        <div className="overflow-y-hidden font-vt bg-[#7287fd] text-text pb-8">
          <Navbar />
          <Hero />
          {children}
        </div>
      </body>
    </html>
  );
}
